export const categoryList = [
    {
      id: 1,
      value: 'men',
      label: 'Men',
    },
    {
      id: 2,
      value: 'women',
      label: 'Women',
    },
    {
      id:3,
      value:'kids',
      label:'Kids',
    }
  ];
  
  export const ratingList = [
    {
      id: 1,
      value: '1',
      label: '1🌟',
    },
    {
      id: 2,
      value: '2',
      label: '2🌟',
    },
    {
      id: 3,
      value: '3',
      label: '3🌟',
    },
    {
      id: 4,
      value: '4',
      label: '4🌟',
    },
    {
      id: 5,
      value: '5',
      label: '5🌟',
    },
  ];
  
  export const dataList = [
    {
      id: 1,
      title: 'Designer Men Kurta Sets',
      category: 'men',
      cuisine: 'traditional',
      rating: 5,
      price: 2500,
      coverSrc: 'https://static01.manyavar.com/uploads/dealimages/13792/zoomimages/bright-rani-pink-kurta-ml12018-325-4.jpg',
    },
    {
      id: 2,
      title: 'Stylish Designer Men Shirts',
      category: 'men',
      cuisine: 'western',
      rating: 4,
      price: 1000,
      coverSrc: 'https://www.myraymond.com/media/product/RISC00455-M7/1054664950_RISC00455-M7(1).jpg',
    },
    {
      id: 3,
      title: 'whiteshirt',
      category: 'men',
      cuisine: 'western',
      rating: 3,
      price: 2000,
      coverSrc: 'https://cms.cloudinary.vpsvc.com/image/upload/c_scale,dpr_auto,f_auto,q_auto:good,w_700/India%20LOB/Clothing%20and%20Bags/Embroidered%20Office%20Shirts%20-Men/IN_Embroidered-Office-Shirts-Men_Overview',
    },
    {
      id: 4,
      title: 'Modern Elegant Girls Frocks',
      category: 'kids',
      cuisine: 'western',
      rating: 3,
      price: 1800,
      coverSrc: 'https://cdn.fcglcdn.com/brainbees/images/products/438x531/10469380a.webp',
    },
    {
      id: 5,
      title: 'Traditional Indian enthic wear',
      category: 'kids',
      cuisine: 'traditional',
      rating: 5,
      price: 2000,
      coverSrc: 'https://i.etsystatic.com/34608543/r/il/4475f6/3807279215/il_1588xN.3807279215_bgrx.jpg',
    },
    {
      id: 6,
      title: 'Qtsy Ethnic Wear kids',
      category: 'kids',
      cuisine: 'traditional',
      rating: 4,
      price: 3500,
      coverSrc: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzGROXTtPbEC2V2J8flCozTgadBGl7lzfiCz47P0O3la5c6BZC1bTGBpCd2Gv0Fv61fqc&usqp=CAU',
    },
    {
      id: 7,
      title: 'Party Wear Maroon Kids Trendy Midi Dress',
      category: 'kids',
      cuisine: 'fashion',
      rating: 2,
      price: 2200,
      coverSrc: 'https://5.imimg.com/data5/LS/IZ/NA/SELLER-99304314/kids-trendy-midi-dress-500x500.jpg',
    },
    {
      id: 8,
      title: 'Flawsome Trendy boys',
      category: 'men',
      cuisine: 'fashion',
      rating: 1,
      price: 1900,
      coverSrc: 'https://i0.wp.com/jaxsonmaximus.com/wp-content/uploads/2020/04/34394c211f01e58539f91e79e6ce1420-400x700.jpg',
    },
    {
      id: 9,
      title: 'Green Modal Silk Churidar Dress For Girls',
      category: 'women',
      cuisine: 'traditional',
      rating: 4,
      price: 2750,
      coverSrc: 'https://www.fabja.com/pub/media/catalog/product/cache/74c1057f7991b4edb2bc7bdaa94de933/g/r/green-modal-silk-churidar-dress-for-girls-fj12240.jpg',
    },
    {
      id: 10,
      title: 'Simplicity Blazer Dress',
      category: 'women',
      cuisine: 'fashion',
      rating: 2,
      price: 4350,
      coverSrc: 'https://img101.urbanic.com/goods-pic/f242f8b674854501b4de06e4a3159f03_w1000_q90',
    },
    {
      id: 11,
      title: 'Trendy Fabulous Women',
      category: 'women',
      cuisine: 'western',
      rating: 3,
      price: 3300,
      coverSrc: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSiLsxMX-g6ULiaJgRCNil6CdRUm2ysgM2wSWESIL6qrkB-RrXXEK9cwpXWD0qcqJewm7ewwQy39JjLecW6qb4Hvir0x65xXdHo82qsNPe2JQ1JnTaS2QI8nw&usqp=CAE',
    },
    {
      id: 12,
      title: 'Banita Alluring Sarees',
      category: 'women',
      cuisine: 'traditional',
      rating: 2,
      price: 4100,
      coverSrc: 'https://cdn.shopify.com/s/files/1/0524/0238/9183/products/6b8d1913-4cc1-4251-acc6-2d34d84d6196_1_800x.jpg?v=1608785497',
    },
  ];